name: Build and Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main, master ]

# Donne les autorisations nécessaires à GitHub pour publier le site
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Fresh Project & Build Web
        run: |
          flutter create fresh_app --platforms=web
          cd fresh_app
          
          # Ajout des extensions compatibles web
          flutter pub add ai_barcode_scanner http intl
          
          # Remplacement du code source
          cp ../lib/main.dart lib/main.dart
          
          # Compilation de l'application en mode Web pour GitHub Pages
          flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: fresh_app/build/web
          branch: gh-pages # Crée une branche spéciale pour le site web