name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Fresh Project & Inject Code
        run: |
          flutter create fresh_app --platforms=android
          cd fresh_app
          flutter pub add mobile_scanner http intl
          
          # Ligne magique : injecte la permission caméra juste après la balise <manifest>
          sed -i '/<manifest xmlns:android="http:\/\/schemas.android.com\/apk\/res\/android">/a \    <uses-permission android:name="android.permission.CAMERA" \/>' android/app/src/main/AndroidManifest.xml
          
          cp ../lib/main.dart lib/main.dart

      - name: Build APK
        run: |
          cd fresh_app
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: fresh_app/build/app/outputs/flutter-apk/app-release.apk